import { existsSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const API = process.env.VITE_API_URL || "https://api.poneglyph.one";
const OUTPUT_PATH = resolve(import.meta.dirname, "../src/decks/cardDictionary.generated.ts");
const MAX_DICTIONARY_SIZE = 1 << 14;

interface CardEntry {
  card_number: string;
}

async function fetchJson<T>(path: string): Promise<T> {
  const response = await fetch(`${API}${path}`);
  if (!response.ok) {
    throw new Error(`${path} returned ${response.status}`);
  }
  return response.json();
}

async function getAllCardNumbers(): Promise<string[]> {
  const cardNumbers: string[] = [];
  let page = 1;

  while (true) {
    const response = await fetchJson<{ data: CardEntry[]; pagination: { has_more: boolean } }>(
      `/v1/cards?unique=cards&limit=250&page=${page}&sort=card_number&order=asc`,
    );

    for (const card of response.data) {
      cardNumbers.push(card.card_number.toUpperCase());
    }

    if (!response.pagination.has_more) {
      break;
    }
    page += 1;
  }

  return cardNumbers;
}

function readExistingDictionary(): string[] {
  if (!existsSync(OUTPUT_PATH)) {
    return [];
  }

  const source = readFileSync(OUTPUT_PATH, "utf8");
  const match = source.match(/export const CARD_DICTIONARY: string\[\] = (\[[\s\S]*?\]);/);
  if (!match) {
    return [];
  }

  try {
    const parsed = JSON.parse(match[1]) as unknown;
    return Array.isArray(parsed)
      ? parsed.filter((value): value is string => typeof value === "string")
      : [];
  } catch {
    return [];
  }
}

function renderDictionary(cardNumbers: string[]) {
  const json = JSON.stringify(cardNumbers, null, 2);

  return [
    "// Generated by scripts/generate-card-dictionary.ts. Do not edit manually.",
    `export const CARD_DICTIONARY: string[] = ${json};`,
    "export const CARD_INDEX_BY_NUMBER = new Map<string, number>(",
    "  CARD_DICTIONARY.map((cardNumber, index) => [cardNumber, index]),",
    ");",
    "",
  ].join("\n");
}

async function main() {
  console.log("Generating card dictionary...");

  const existing = readExistingDictionary();
  const existingSet = new Set(existing.map((value) => value.toUpperCase()));
  const next = [...existing];
  const fetched = await getAllCardNumbers();

  for (const cardNumber of fetched) {
    if (!existingSet.has(cardNumber)) {
      existingSet.add(cardNumber);
      next.push(cardNumber);
    }
  }

  if (next.length > MAX_DICTIONARY_SIZE) {
    throw new Error(`Card dictionary exceeded ${MAX_DICTIONARY_SIZE} entries; deck hash format must be revised.`);
  }

  writeFileSync(OUTPUT_PATH, renderDictionary(next), "utf8");
  console.log(`Wrote ${next.length} card ids to ${OUTPUT_PATH}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
